---
- name: Deploy Miscorervice Stack
  hosts: node01
  become: yes
  roles:
    - application

- name: Deploy Web Server
  hosts: node02
  become: yes
  roles:
    - apache

- name: Deploy PostgreSQL Server
  hosts: node02
  become: yes
  roles:
    - postgres
