---
- name: Установка PostgreSQL и зависимостей
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2    # <--- Драйвер для модулей Ansible
      - acl                 # <--- Утилита для become_user
    update_cache: true

- name: Запуск службы PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Содание БД hotels_db
  community.postgresql.postgresql_db:
    name: hotels_db
    state: present
  become: true
  become_user: postgres

- name: Установка пароля для пользователя postgres
  community.postgresql.postgresql_user:
    name: postgres
    password: "postgres" # в проде конечно лучше поменять будет
  become: true
  become_user: postgres
