[api_servers]
api  ansible_host=192.168.56.11 ansible_user=vagrant

[db_servers]
db ansible_host=192.168.56.13 ansible_user=vagrant

[consul_servers]
consul_server ansible_host=192.168.56.10 ansible_user=vagrant

[consul_clients]
api
db

[all:vars]
ansible_python_interpreter=/usr/bin/python3